# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3abb7c73cd51b21ae2920b636f6caa8fa1343401f61eaa3b5e24a76796efd0354e93fb9f77d5d2edcd5ff3ccd174f8efb445445d5cf7e2b47d6f0c51ab63bc6

test:
  secret_key_base: 692b80036e4252ccde5dcb5acce8af966005f0bf8f312bc521d4988c24467afda10b065aa2edd05c0106e34ef5004788090f67e198314cfe089e90772cdf10f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
